dataset: SAA  # Name of the hyperspectral dataset (options: 'SAA', 'IP', 'SA', 'PU', 'SD', 'HP')
target_class_num: 12  # Target class number for binary classification (integer)
num_components: 3  # Number of PCA components to retain (integer, typically 3-10)
window_size: 5  # Size of the patch window (must be odd, e.g., 3, 5, 7)
test_ratio: 0.1  # Proportion of data for testing (float between 0 and 1)
seed_value: 7  # Random seed for reproducibility (integer)
batch_size: 32  # Batch size for model training (integer, power of 2 recommended)
epochs: 10  # Maximum number of training epochs (integer)
learning_rate: 0.01  # Learning rate for the Adam optimizer (float, e.g., 0.001, 0.01)
patience: 3  # Number of epochs to wait for early stopping (integer)
data_path: ../HSI_Datasets/  # Path to the dataset directory (end with slash)
model_name: ../models/TargetDetection_{}_{}.keras  # Template for saved model filename ({} is replaced by dataset name)